### ISSUE TITLE
Moze jednostavnije :)

### ISSUE THREAD

**Issue by igr** [Evizzo/ATM-Banking-System#5]
https://github.com/Evizzo/ATM-Banking-System/blob/11366e4dd016303ee2a22a1a41762763d5b572dd/src/main/java/com/example/atmbankingsystem/Controller.java#L101

**Comment by igr** [comment]
Math.randomInt (ako se dobro secam)

**Comment by Evizzo** [comment]
Ne mogu da nadjem nista slicno funkciji "Math.randomInt", ima samo "Math.random" koji koristim
Pogledao sam i u dokumentaciji, nisam uspeo da pronadjem
https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/Math.html

**Comment by igr** [comment]
Druga klasa je u pitanju: https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/Random.html#nextInt(int)
